{% set name = "boa" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mamba-org/boa/archive/{{ version }}.tar.gz
  sha256: f579557f7d93fedf07615d0da909f676039f6e52210f72b34f4364f344595db0

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0
  noarch: python
  entry_points:
    - conda-mambabuild = boa.cli.mambabuild:main
    - boa = boa.cli.boa:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - conda-build >=3.24,<3.25
    - mamba >=1.0,<1.5
    - ruamel.yaml
    - jinja2
    - rich
    - prompt_toolkit
    - json5
    - jsonschema
    - joblib
    - watchgod
    # for python 3.6 compatibility
    - dataclasses

test:
  imports:
    - boa
    - boa.cli
  commands:
    - boa -h

about:
  home: https://github.com/mamba-org/boa
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The mamba-powered conda package builder

extra:
  recipe-maintainers:
    - wolfv
    - JohanMabille
    - isuruf
    - mbargull
